apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-deployment
  labels:
    app: scale-deployment
spec:
  replicas: ##Replicas##
  selector:
    matchLabels:
      app: scale-deployment
  template:
    metadata:
      labels:
        app: scale-deployment
    spec:
      containers:
        - name: nginx
          image: mcr.microsoft.com/cbl-mariner/base/nginx:1
          resources:
            requests:
              cpu: ##CPUperJob##
            limits:
              cpu: ##CPUperJob##
          command:
          - "/bin/bash"
          - "-c"
          - runtime="1 minute"; endtime=$(date -ud "$runtime" +%s); while [[ $(date -u +%s) -le $endtime ]]; do echo $(date); sleep 6000; done
      restartPolicy: Always
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
