apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: client-
resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: false
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          app: client
      - op: add
        path: /spec/template/spec/containers/0/name
        value: iperf3-client
      - op: add
        path: /spec/template/spec/containers/0/args
        value: ["-c", "ldconfig; sleep infinity"]
    target:
      kind: Deployment
      name: iperf3-deployment
labels:
  - includeSelectors: true
    pairs:
      app: iperf3-client
