{{$action := .action}} # start, gather

steps:
  - name: {{$action}} Kubelet Measurements
    measurements:
    - Identifier: KubeletRuntimeOperationDurationWithoutPullImage
      Method: GenericPrometheusQuery
      Params:
        action: {{$action}}
        metricName: KubeletRuntimeOperationDurationWithoutPullImage
        metricVersion: v1
        unit: s
        dimensions:
          - node
          - operation_type
        queries:
        - name: Perc99
          query: histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{operation_type!="pull_image"}[10m])) by (node, operation_type, le))
        - name: Perc75
          query: histogram_quantile(0.75, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{operation_type!="pull_image"}[10m])) by (node, operation_type, le))
        - name: Perc50
          query: histogram_quantile(0.50, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{operation_type!="pull_image"}[10m])) by (node, operation_type, le))
        - name: Sum
          query: kubelet_runtime_operations_duration_seconds_sum{operation_type!="pull_image"}
    - Identifier: KubeletRuntimeOperationDurationWithPullImage
      Method: GenericPrometheusQuery
      Params:
        action: {{$action}}
        metricName: KubeletRuntimeOperationDurationWithPullImage
        metricVersion: v1
        unit: s
        dimensions:
          - node
          - operation_type
        queries:
        - name: Perc99
          query: histogram_quantile(0.99, sum(avg_over_time(kubelet_runtime_operations_duration_seconds_bucket{operation_type="pull_image"}[5m])) by (node, operation_type, le))
        - name: Perc75
          query: histogram_quantile(0.75, sum(avg_over_time(kubelet_runtime_operations_duration_seconds_bucket{operation_type="pull_image"}[5m])) by (node, operation_type, le))
        - name: Perc50
          query: histogram_quantile(0.50, sum(avg_over_time(kubelet_runtime_operations_duration_seconds_bucket{operation_type="pull_image"}[5m])) by (node, operation_type, le))
        - name: Sum
          query: kubelet_runtime_operations_duration_seconds_sum{operation_type="pull_image"}
