---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-sut
  namespace: slo-1
  labels:
    app: perf-sut
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perf-sut
  template:
    metadata:
      labels:
        app: perf-sut
        podgroup: deployment-churn
        scenario: datapath-test
    spec:
      serviceAccountName: reporter-sa
      initContainers:
      - name: reporter
        image: acndev.azurecr.io/datapath-reporter:2025.12.29.01
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROBE_TARGET
          value: "http://172.27.0.30:80"  # nginx service IP in customer cluster
        - name: PROBE_TIMEOUT
          value: "60"  # seconds
        - name: PROBE_INTERVAL
          value: "2"   # seconds
      containers:
      - image: acndev.azurecr.io/netshoot:latest
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        name: deployment-churn
        resources:
          requests:
            acn.azure.com/vnet-nic: "1"
          limits:
            acn.azure.com/vnet-nic: "1"
        ports:
