---
apiVersion: v1
kind: Namespace
metadata:
  name: perf-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter-sa
  namespace: perf-ns
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-selfpatch
  namespace: perf-ns
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-selfpatch
  namespace: perf-ns
subjects:
- kind: ServiceAccount
  name: reporter-sa
  namespace: perf-ns
roleRef:
  kind: Role
  name: reporter-selfpatch
  apiGroup: rbac.authorization.k8s.io
