apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datapathresults.perf.github.com
spec:
  group: perf.github.com
  names:
    kind: DatapathResult
    listKind: DatapathResultList
    plural: datapathresults
    singular: datapathresult
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: DatapathResult is the Schema for the datapathresults API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: DatapathResultSpec defines the desired state of DatapathResult
            properties:
              podRef:
                properties:
                  namespace:
                    type: string
                  name:
                    type: string
                  uid:
                    type: string
                required:
                - namespace
                - name
                - uid
                type: object
              timestamps:
                properties:
                  createdAt:
                    type: string
                  startTs:
                    type: string
                  dpReadyTs:
                    type: string
                required:
                - createdAt
                type: object
              metrics:
                properties:
                  latStartMs:
                    type: integer
                    format: int64
                  latDpReadyMs:
                    type: integer
                    format: int64
                type: object
              labels:
                additionalProperties:
                  type: string
                type: object
            required:
            - podRef
            - timestamps
            - metrics
            type: object
          status:
            description: DatapathResultStatus defines the observed state of DatapathResult
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
