apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapath-controller
  namespace: perf-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datapath-controller
  template:
    metadata:
      labels:
        app: datapath-controller
    spec:
      serviceAccountName: datapath-controller
      containers:
      - name: controller
        image: acndev.azurecr.io/datapath-controller:2025.12.29.01
        args:
        - "--namespace=perf-ns"
        - "--label-selector=app=perf-sut"
        - "--slo-start=30s"
        - "--slo-dpready=60s"
        ports:
        - name: http
          containerPort: 8080
