apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapath-controller
  namespace: perf-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapath-controller
  template:
    metadata:
      labels:
        app: datapath-controller
    spec:
      nodeSelector:
        kubernetes.azure.com/mode: system
      serviceAccountName: datapath-controller
      containers:
      - name: controller
        image: acndev.azurecr.io/datapath-controller:2026.01.13.01
        args:
        - "--namespace=slo-1"
        - "--label-selector=podgroup=deployment-churn"
        - "--max-concurrent-reconciles=100"
        ports:
        - name: metrics
          containerPort: 8080
        - name: http
          containerPort: 8082
