apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-datapath-watcher
  namespace: perf-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-datapath-watcher
  template:
    metadata:
      labels:
        app: pod-datapath-watcher
    spec:
      serviceAccountName: pod-datapath-watcher
      containers:
      - name: watcher
        image: acndev.azurecr.io/pod-datapath-watcher:2025.12.29.01
        args:
        - "--namespace=perf-ns"
        - "--label-selector=app=perf-sut"
        - "--slo-start=30s"
        - "--slo-dpready=60s"
        ports:
        - name: http
          containerPort: 8080
