apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-datapath-watcher
  namespace: perf-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-datapath-watcher
  namespace: perf-ns
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["perf.github.com/Azure"]
  resources: ["datapathresults"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-datapath-watcher
  namespace: perf-ns
subjects:
- kind: ServiceAccount
  name: pod-datapath-watcher
  namespace: perf-ns
roleRef:
  kind: Role
  name: pod-datapath-watcher
  apiGroup: rbac.authorization.k8s.io
