apiVersion: v1
kind: Namespace
metadata:
  name: perf-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datapath-controller
  namespace: perf-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datapath-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["perf.github.com/Azure"]
  resources: ["datapathresults"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datapath-controller
subjects:
- kind: ServiceAccount
  name: datapath-controller
  namespace: perf-ns
roleRef:
  kind: ClusterRole
  name: datapath-controller
  apiGroup: rbac.authorization.k8s.io
