apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nfd-network-rule
spec:
  rules:
    - name: "nfd-network-rule"
      labels:
        "feature.node.kubernetes.io/pci-15b3.present": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            # Infiniband controller [0207]: Mellanox Technologies MT28908 Family [ConnectX-6 Virtual Function] [15b3:101c]
            device: { op: In, value: ["101c", "101e"] }
