---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter-sa
  namespace: {{.Namespace}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-selfpatch
  namespace: {{.Namespace}}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-selfpatch
  namespace: {{.Namespace}}
subjects:
- kind: ServiceAccount
  name: reporter-sa
  namespace: {{.Namespace}}
roleRef:
  kind: Role
  name: reporter-selfpatch
  apiGroup: rbac.authorization.k8s.io
