kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
subjects:
- kind: ServiceAccount
  name: reporter-sa-0
  namespace: {{.Namespace}}
roleRef:
  kind: Role
  name: reporter-role-0
  apiGroup: rbac.authorization.k8s.io
