kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
- apiGroups: ["multitenancy.acn.azure.com"]
  resources: ["podnetworkinstances"]
  verbs: ["get", "list"]
