{{$action := .action}} # start, gather

# Feature gates
{{$podStartupLatencyThreshold := DefaultParam .CL2_POD_STARTUP_LATENCY_THRESHOLD "15s"}}
{{$ENABLE_VIOLATIONS_FOR_API_CALL_PROMETHEUS_SIMPLE := DefaultParam .CL2_ENABLE_VIOLATIONS_FOR_API_CALL_PROMETHEUS_SIMPLE true}}
{{$PROMETHEUS_SCRAPE_KUBE_PROXY := DefaultParam .PROMETHEUS_SCRAPE_KUBE_PROXY true}}
{{$NETWORK_PROGRAMMING_LATENCY_THRESHOLD := DefaultParam .CL2_NETWORK_PROGRAMMING_LATENCY_THRESHOLD "30s"}}
{{$ENABLE_VIOLATIONS_FOR_NETWORK_PROGRAMMING_LATENCIES := DefaultParam .CL2_ENABLE_VIOLATIONS_FOR_NETWORK_PROGRAMMING_LATENCIES false}}
{{$NETWORK_LATENCY_THRESHOLD := DefaultParam .CL2_NETWORK_LATENCY_THRESHOLD "0s"}}
{{$PROBE_MEASUREMENTS_PING_SLEEP_DURATION := DefaultParam .CL2_PROBE_MEASUREMENTS_PING_SLEEP_DURATION "1s"}}
{{$ENABLE_IN_CLUSTER_NETWORK_LATENCY := DefaultParam .CL2_ENABLE_IN_CLUSTER_NETWORK_LATENCY true}}

# Probe measurements shared parameter
{{$PROBE_MEASUREMENTS_CHECK_PROBES_READY_TIMEOUT := DefaultParam .CL2_PROBE_MEASUREMENTS_CHECK_PROBES_READY_TIMEOUT "15m"}}
{{$ENABLE_TERMINATED_WATCHES_MEASUREMENT := DefaultParam .CL2_ENABLE_TERMINATED_WATCHES_MEASUREMENT true}}

steps:
  - name: {{$action}} Additional Measurements
    measurements:
      - Identifier: APIResponsivenessPrometheus
        Method: APIResponsivenessPrometheus
        Params:
          action: {{$action}}
          enableViolations: {{$ENABLE_VIOLATIONS_FOR_API_CALL_PROMETHEUS_SIMPLE}}
          useSimpleLatencyQuery: true
      - Identifier: PodStartupLatency
        Method: PodStartupLatency
        Params:
          action: {{$action}}
          labelSelector: group = {{.group}}
          threshold: {{$podStartupLatencyThreshold}}
    {{if $PROMETHEUS_SCRAPE_KUBE_PROXY}}
      - Identifier: NetworkProgrammingLatency
        Method: NetworkProgrammingLatency
        Params:
          action: {{$action}}
          enableViolations: {{$ENABLE_VIOLATIONS_FOR_NETWORK_PROGRAMMING_LATENCIES}}
          threshold: {{$NETWORK_PROGRAMMING_LATENCY_THRESHOLD}}
    {{end}}
    {{if $ENABLE_IN_CLUSTER_NETWORK_LATENCY}}
      - Identifier: InClusterNetworkLatency
        Method: InClusterNetworkLatency
        Params:
          action: {{$action}}
          checkProbesReadyTimeout: {{$PROBE_MEASUREMENTS_CHECK_PROBES_READY_TIMEOUT}}
          replicasPerProbe: {{AddInt 2 (DivideInt .Nodes 100)}}
          pingSleepDuration: {{$PROBE_MEASUREMENTS_PING_SLEEP_DURATION}}
          threshold: {{$NETWORK_LATENCY_THRESHOLD}}
    {{end}}
    {{if $ENABLE_TERMINATED_WATCHES_MEASUREMENT}}
      - Identifier: TerminatedWatchesMetrics
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Terminated Watches
          metricVersion: v1
          unit: count
          dimensions:
          - resource
          queries:
          - name: Terminated watches
            query: sum(increase(apiserver_terminated_watchers_total[%v:])) by (resource)
    {{end}}
      - Identifier: ApiserverAvgCPUUsage
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver Average CPU Usage
          metricVersion: v1
          unit: cpu
          enableViolations: true
          queries:
          - name: Perc99
            query: quantile(0.99, avg_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
          - name: Perc90
            query: quantile(0.90, avg_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
          - name: Perc50
            query: quantile(0.50, avg_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
      - Identifier: ApiserverMaxCPUUsage
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver Max CPU Usage
          metricVersion: v1
          unit: cpu
          enableViolations: true
          queries:
          - name: Perc99
            query: quantile(0.99, max_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
          - name: Perc90
            query: quantile(0.90, max_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
          - name: Perc50
            query: quantile(0.50, max_over_time(rate(process_cpu_seconds_total{endpoint="apiserver"}[1m])[%v:]))
      - Identifier: ApiserverAvgMemUsage
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver Avg Memory Usage
          metricVersion: v1
          unit: MB
          enableViolations: true
          queries:
          - name: Perc99
            query: quantile(0.99, avg_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
          - name: Perc90
            query: quantile(0.90, avg_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
          - name: Perc50
            query: quantile(0.5, avg_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
      - Identifier: ApiserverMaxMemUsage
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver Max Memory Usage
          metricVersion: v1
          unit: MB
          enableViolations: true
          queries:
          - name: Perc99
            query: quantile(0.99, max_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
          - name: Perc90
            query: quantile(0.90, max_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
          - name: Perc50
            query: quantile(0.5, max_over_time(process_resident_memory_bytes{endpoint="apiserver"}[%v:]) / 1024 / 1024)
      - Identifier: apiserver_request_total
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver Request Total by verb, resource, job
          metricVersion: v1
          unit: count
          enableViolations: true
          queries:
          - name: Apiserver Request Total by verb and resource
            query:  sum(rate(apiserver_request_total[1m])) by (verb, resource, job)
      - Identifier: apiserver_request_duration_seconds 
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Api requests latency by verb, resource
          metricVersion: v1
          unit: s
          enableViolations: true
          queries:
          - name: Perc99
            query:  histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le, verb, resource))
          - name: Perc90
            query:  histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le, verb, resource))
          - name: Perc50
            query:  histogram_quantile(0.50, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le, verb, resource))
      - Identifier: apiserver_storage_objects
        Method: GenericPrometheusQuery
        Params:
          action: {{$action}}
          metricName: Apiserver stored objects per resource
          metricVersion: v1
          unit: count
          enableViolations: true
          queries:
          - name: Objects stored by resource
            query:  sum(apiserver_storage_objects) by (resource)
